### ISSUE TITLE
Nicht nur bei IMAGES

### ISSUE THREAD

**Issue by niceoneilike** [xportde/JensParallax#1]
Parallax soll nicht nur auf IMAGES funktionieren, am besten auf classen damit man auch picture-Element verwenden kann.

**Comment by pgml** [comment]
Geht eigentlich schon.
Das Picture-Element braucht nur die Klasse »parallaxImage«.
Das könnte man alternativ auch als Option beim jQuery-Aufruf zur Auswahl machen.

```
<div class="parallax">
  <picture class="image parallaxImage">
    <source media="(max-width: 480px)" srcset="image.jpg">
    <source media="(max-width: 740px)" srcset="image.jpg">
    <source media="(max-width: 980px)" srcset="image.jpg">
    <source media="(max-width: 1280px)" srcset="image.jpg">
    <source media="(max-width: 1680px)" srcset="image.jpg">
    <img class="image" src="image.jpg" alt="">
  </picture>
</div>
```

**Comment by niceoneilike** [comment]
Die klasse sollte aber nicht dafür da sein. Dann nimm bitte lieber eine andere die klasse `.parallaxImage` ist für den Parallax :D. Mach lieber `.picture`  draus

**Comment by niceoneilike** [comment]
Also zusätzlich .picture
